project_id = "rbzmojurvypksubeigbt"

[functions.enviar-link-email]
verify_jwt = true

[functions.generate-exercise-image]
verify_jwt = true

[functions.voice-assessment]
verify_jwt = false

[functions.validar-myid-token]
verify_jwt = false
